### PR TITLE
add an environment variable to specify databases to download

### PR DESCRIPTION
**Pull request by vincentbernat**

### CODE REVIEW

**Comment by abdullahdevrel** [comment]
Thank you very much for the PR, @vincentbernat. Really appreciate it. Pinging our head of backend and integrations, @UmanShahzad. 

Uman, Vincent is the core maintainer of the [Avokadro](https://github.com/akvorado/akvorado). He was very kind to adopt our free database in his project recently.

**Review by UmanShahzad — APPROVED** [review]

**Comment by UmanShahzad** [comment]
Thanks for the contrib @vincentbernat !

**Comment by UmanShahzad** [comment]
@abu-usama can we run the upload script with an updated version?

**Comment by abu-usama** [comment]
The docker image now reflects the latest version.
CC: @vincentbernat @UmanShahzad

**Pull request merged**
